### PR TITLE
Include options in README.

### PR DESCRIPTION
**Pull request by facundobatista**

### CODE REVIEW

**Comment by thesharp** [comment]
Hello @facundobatista.

Did you read the [documentation at readthedocs](http://daemonize.readthedocs.org)? It has that exact thing, you've inserted into README.rst, except it is generated automatically from the source code.

**Comment by facundobatista** [comment]
Hi thesharp!

It happened to me and to a friend that we looked at the info in PyPI, and then at the README in github, and docs were not good.

We didn't thought about going into readthedocs. 

Maybe you could incorporate a link to readthedocs into the README?

**Comment by thesharp** [comment]
There is one at the top, near the build status.

**Comment by facundobatista** [comment]
Ah, that fancy button! Thanks!

**Pull request closed without merging**
